project:
  type: book

book:
  title: "Ecosystem Status Report Best Practices Document"
  author: "Gulf IEA"
  date: today
  chapters:
    - index.qmd
    - content/start.qmd
    - content/indicator_scoping.qmd
    - content/data_processing.qmd
    - content/report_writing.qmd
    - Glossary.qmd

format:
  html:
    theme: cosmo # Or another theme like 'flatly', 'journal', etc.
    toc: true
    toc-depth: 2
  pdf:
    documentclass: scrreprt # Or 'article', 'book', etc.
    toc: true
    number-sections: true
    pdf-engine: lualatex # Or 'xelatex', 'pdflatex'
